### ISSUE TITLE
Does the plugin support background images, where the path to image is via the CSS stylesheet?

### ISSUE THREAD

**Issue by imohkay** [kvendrik/responsive-images.js#6]
Not sure if this is the right place for this question, but am curious. Overall the plugin looks great and background image support would be wonderful :)

**Comment by kvendrik** [comment]
Hi Imogkay,

Glad you like the plugin! :) It doesn't support background images because they can be safely made responsive using [media queries](http://webdesignerwall.com/tutorials/css3-media-queries).

The browser only preloads `img` tags with a `src` attribute and not background images that are defined in the CSS. This means that the images you request in your CSS are not loaded until the CSS is being processed. Therefor, you can easily make them responsive using media queries.

If you are worried about this not working in IE8 and below then have a look at [scottjehl's media query polyfill](https://github.com/scottjehl/Respond) which makes sure media queries work in older versions of IE.

I hope that was a good answer to your question, let me know what you think. :)

**Comment by imohkay** [comment]
Thanks so much. Yes this answers my question :)
